# Generated by Django 3.2.5 on 2022-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_post_mainphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.TextField()),
                ('age', models.TextField()),
                ('season', models.TextField()),
                ('genre', models.TextField()),
                ('story', models.TextField()),
                ('people', models.TextField()),
                ('title_sp', models.TextField()),
                ('url_text', models.TextField()),
            ],
        ),
    ]
