# Generated by Django 3.2.5 on 2022-02-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_title_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title_data',
            name='url_text',
        ),
        migrations.AddField(
            model_name='title_data',
            name='photo',
            field=models.ImageField(blank=True, upload_to='items', verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='title_data',
            name='url_photo',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL'),
        ),
    ]
