# Generated by Django 3.2.5 on 2022-02-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_title_data_recommend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title_data',
            old_name='recommend',
            new_name='recommend_code',
        ),
        migrations.AddField(
            model_name='title_data',
            name='recommend_title',
            field=models.TextField(blank=True),
        ),
    ]
