# Generated by Django 3.2.5 on 2022-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20220217_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title_data',
            old_name='recommend_code',
            new_name='re_code',
        ),
        migrations.RenameField(
            model_name='title_data',
            old_name='recommend_title',
            new_name='re_title',
        ),
        migrations.AlterField(
            model_name='title_data',
            name='photo_url',
            field=models.URLField(blank=True, max_length=350, verbose_name='URL'),
        ),
    ]
